name: mine-player

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - openjdk=21
  - cmake
  - glew
  - libpng
  - libzlib
  - libopengl
  - libflite
  - opencv
  - pip:
      - craftground==2.7.4
